name: Generate GitHub API types
on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    strategy:
      matrix:
        schema:
          - url: https://github.com/github/rest-api-description/raw/main/descriptions/api.github.com/api.github.com.yaml
            output: ./mod.ts

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: auto/update

      - name: Generate TypeScript types from OpenAPI schema
        id: update
        run: |
          npx openapi-typescript ${{ matrix.schema.url }} --output ${{ matrix.schema.output }}

          # Check if there have been any git changes. updated=1 if there's one,
          # otherwise it's 0. We'll skip the rest if 0.
          if [[ $(git status --short) ]]; then
            echo "updated=1" >> $GITHUB_OUTPUT
          else
            echo "updated=0" >> $GITHUB_OUTPUT
          fi

          # Git add if the changes are untracked.
          git add ${{ matrix.schema.output }}

      - name: Commit changes, if any
        id: git-commit
        if: steps.update.outputs.updated == 1
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |-
            Update github_api_types using GitHub Actions
            The action workflow was triggered by ref:
                ${{ github.sha }}
