name: Generate GitHub API types
on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        schema:
          - url: https://github.com/github/rest-api-description/raw/main/descriptions/api.github.com/api.github.com.yaml
            output: mod.ts
          - url: https://github.com/github/rest-api-description/raw/main/descriptions/api.github.com/api.github.com.2022-11-28.yaml
            output: api.github.com.2022-11-28/mod.ts

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate TypeScript types from OpenAPI schema
        run: |
          npx openapi-typescript ${{ matrix.schema.url }} --output ${{ matrix.schema.output }}

          # Check if there has been any git changes. updated=1 if there's one,
          # otherwise it's 0. We'll skip the rest if 0.
          if [[ $(git status --porcelain) ]]; then
            echo "updated=1" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes, if any
        id: git-commit
        if: steps.update-pkg.outputs.updated == 1
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |-
            Update github_api_types using GitHub Actions
            The action workflow was triggered by ref:
                ${{ github.sha }}
          branch: ${{ github.ref_name }}
