name: Manual Branch Promotion

on:
  schedule:
    - cron: "0 0 * * 1" # At 12:00 AM on Monday
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name"
        required: true
        default: "auto/update"

jobs:
  promote_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current datetime
        id: get_datetime
        run: echo "datetime=$(date -u +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Get latest auto/update sha
        id: get_sha
        run: echo "sha=$(git rev-parse ${{ github.event.inputs.branch }})" >> $GITHUB_ENV

      - name: Promote branch to main
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          script: |
            await github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "heads/main",
              sha: "${{ env.sha }}",
              force: true
            })

      - name: Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          name: "Recurring release ${{ env.datetime }}"
          tag_name: ${{ env.datetime }}
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          body: "Deno module: https://deno.land/x/github_api_types@${{ env.datetime }}"
          generate_release_notes: true
          draft: false
          prerelease: false
