name: Manual Branch Promotion

# Trigger the workflow on manual dispatch event
on:
  schedule:
    - cron: "0 0 * * *" # https://crontab.guru/#0_9_*_*_1 (At 9:00 AM on Monday)
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name"
        required: true
        default: "auto/update"

jobs:
  promote_to_main:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Promote branch to main
        run: |-
          # Fetch the specified branch from origin
          git fetch origin ${{ github.event.inputs.branch }}:${{ github.event.inputs.branch }}

          # Checkout the specified branch
          git checkout ${{ github.event.inputs.branch }}

          # Check if the specified branch is up to date with main
          git fetch origin main

          # Check if there are changes between the specified branch and main
          if git diff --quiet origin/main; then
            echo "No changes between ${{ github.event.inputs.branch }} and main"
            exit 0
          fi

          # Merge the specified branch into main
          git merge --no-ff --no-edit ${{ github.event.inputs.branch }}

          # Push the changes to main
          git push origin main

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Recurring release

          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          generate_release_notes: true
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
