name: Manual Branch Promotion

on:
  schedule:
    - cron: "0 0 * * 1" # At 12:00 AM on Monday
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name"
        required: true
        default: "auto/update"

jobs:
  promote_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Promote branch to main
        id: promote
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch
          git checkout main
          git pull
          git checkout auto/update
          git pull

          if git diff --name-only --diff-filter=U | grep -q .; then
            echo "There are conflicts between main and auto/update. Merge aborted."
            exit 1
          fi

          git checkout main
          git merge --strategy=ours auto/update -m "Merge auto/update into main"
          git push origin main

          echo "datetime=$(date -u +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV
          echo "success=1" >> $GITHUB_ENV

      - name: Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          name: "Recurring release ${{ env.datetime }}"
          tag_name: ${{ env.datetime }}
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          generate_release_notes: true
          draft: false
          prerelease: false
