name: Manual Branch Promotion

# Trigger the workflow on manual dispatch event
on:
  schedule:
    - cron: "0 0 * * 1" # https://crontab.guru/#0_0_*_*_1 (At 12:00 AM on Monday)
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name"
        required: true
        default: "auto/update"

jobs:
  promote_to_main:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Promote branch to main
        id: promote
        run: |-
          # Switch to the source branch. If it doesn't exist, exit.
          git checkout ${{ github.event.inputs.branch }}

          # Merge the latest changes from main into the source branch.
          git merge main

          # Check if there are changes between the specified branch and main.
          if git diff --quiet origin/main; then
            echo "No changes between ${{ github.event.inputs.branch }} and main"
            exit 0
          fi

          # Switch to the target branch (main)   
          git checkout main

          # If the reset was successful, set success=1, otherwise set success=0 and exit.
          if git reset --hard ${{ github.event.inputs.branch }}; then
            echo "success=1" >> $GITHUB_ENV
          else
            echo "success=0" >> $GITHUB_ENV
            exit 1
          fi

          # Output the formatted datetime
          datetime=$(date -u +"%Y-%m-%d-%H-%M")
          echo "datetime=$datetime" >> $GITHUB_ENV

      - name: Release
        if: ${{ steps.promote.outputs.success == 1 }}
        uses: softprops/action-gh-release@v1
        with:
          name: Recurring release
          tag: ${{ steps.promote.outputs.datetime }}
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          generate_release_notes: true
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
