name: Manual Branch Promotion

on:
  schedule:
    - cron: "0 0 * * 1" # At 12:00 AM on Monday
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name"
        required: true
        default: "auto/update"

jobs:
  promote_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current datetime
        run: echo "datetime=$(date -u +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Promote branch to main
        uses: devmasx/merge-branch@1.4.0
        with:
          from_branch: "auto/update"
          target_branch: "main"
          github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          name: "Recurring release ${{ env.datetime }}"
          tag_name: ${{ env.datetime }}
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          generate_release_notes: true
          draft: false
          prerelease: false
