name: Manual Branch Promotion

# Trigger the workflow on manual dispatch event
on:
  schedule:
    - cron: "0 0 * * 1" # https://crontab.guru/#0_0_*_*_1 (At 12:00 AM on Monday)
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name"
        required: true
        default: "auto/update"

jobs:
  promote_to_main:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Promote branch to main
        id: promote
        run: |-
          # Set Git config
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Check if the branch exists
          git fetch
          git checkout main
          git pull
          git checkout auto/update
          git pull

          # Check if there are any conflicts
          if git diff --name-only --diff-filter=U | grep -q .; then
            echo "There are conflicts between main and auto/update. Merge aborted."
            exit 1
          fi

          # If all checks pass, proceed with merging
          git checkout main
          git merge --no-ff auto/update -m "Merge auto/update into main"
          git push origin main

          # Output the formatted datetime
          datetime=$(date -u +"%Y-%m-%d-%H-%M")
          echo "datetime=$datetime" >> $GITHUB_OUTPUT

          # Output success
          echo "success=1" >> $GITHUB_OUTPUT

      - name: Release
        if: ${{ steps.promote.outputs.success == 1 }}
        uses: softprops/action-gh-release@v1
        with:
          name: Recurring release `${{ steps.promote.outputs.datetime }}`
          tag_name: ${{ steps.promote.outputs.datetime }}
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          generate_release_notes: true
          draft: false
          prerelease: false
